In [1]:
import pandas as pd
import numpy as np
import csv

In [2]:
df = pd.read_csv('NYPD_Complaint_Data_Historic-2.csv')
df.head()

FileNotFoundError: [Errno 2] File NYPD_Complaint_Data_Historic-2.csv does not exist: 'NYPD_Complaint_Data_Historic-2.csv'

In [3]:
# Choose specific columns
df_new = df[['CMPLNT_FR_DT','Latitude','Longitude','PATROL_BORO']]
df_new.head()

NameError: name 'df' is not defined

In [9]:
#drop null values
df_new = df_new.dropna()

In [16]:
#only keep 2019 data
df_new['CMPLNT_FR_DT'] = df_new['CMPLNT_FR_DT'].str.split('/').str.get(2)
df_final = df_new[df_new['CMPLNT_FR_DT'] == '2019']

        CMPLNT_FR_DT   Latitude  Longitude                PATROL_BORO
0               2014  40.685041 -73.921777    PATROL BORO BKLYN NORTH
1               2016  40.636991 -74.134093  PATROL BORO STATEN ISLAND
2               2012  40.823876 -73.891863          PATROL BORO BRONX
3               2015  40.845707 -73.910398          PATROL BORO BRONX
4               2017  40.763992 -73.828426   PATROL BORO QUEENS NORTH
...              ...        ...        ...                        ...
6983202         2014  40.808374 -73.946886      PATROL BORO MAN NORTH
6983203         2012  40.648648 -73.967731    PATROL BORO BKLYN SOUTH
6983204         2013  40.716045 -73.964163    PATROL BORO BKLYN NORTH
6983205         2015  40.735211 -73.991691      PATROL BORO MAN SOUTH
6983206         2012  40.667573 -73.907296    PATROL BORO BKLYN NORTH

[6953025 rows x 4 columns]

In [31]:
#sample only 10000 data
df_sample= df_final.sample(n=10000)
df_sample

        CMPLNT_FR_DT   Latitude  Longitude               PATROL_BORO
4518262         2019  40.747044 -73.987128     PATROL BORO MAN SOUTH
4305316         2019  40.690658 -73.864497  PATROL BORO QUEENS SOUTH
4204583         2019  40.719956 -73.938616   PATROL BORO BKLYN NORTH
4099675         2019  40.679284 -73.929059   PATROL BORO BKLYN NORTH
4267311         2019  40.848972 -73.908879         PATROL BORO BRONX
...              ...        ...        ...                       ...
4214347         2019  40.763284 -73.971642     PATROL BORO MAN SOUTH
4525035         2019  40.765421 -73.743659  PATROL BORO QUEENS NORTH
4507381         2019  40.752552 -73.767761  PATROL BORO QUEENS NORTH
4457097         2019  40.692967 -73.896857  PATROL BORO QUEENS NORTH
4117887         2019  40.718440 -73.982938     PATROL BORO MAN SOUTH

[10000 rows x 4 columns]

In [40]:
#export to csv
Result ='/Users/tylin/Downloads/sampled crime.csv'

df_sample.to_csv('sampled_crime.csv' )